### ISSUE TITLE
Does it make sense to switch off the in-application update for Flatpak installs?

### ISSUE THREAD

**Issue by buchen** [flathub/info.portfolio_performance.PortfolioPerformance#50]
My understanding is that a flatpak application should only be update via flatpak.
Does it make sense to deactivate the embedded upgrade mechanism?

If you are interested, I could add a flag that deactivates the check for new versions.
The installer would set the flag (for example in the config.ini that is today changing the workspace folder).

**Comment by roshanshariff** [comment]
That would be great, thanks! Yeah, it's a good idea to disable updates (which probably wouldn't succeed anyway in a Flatpak environment, since the installation directory is read-only).
