### ISSUE TITLE
JVM terminated error on start

### ISSUE THREAD

**Issue by peastea** [flathub/info.portfolio_performance.PortfolioPerformance#53]
Flatpak run throws error on startup on Linux Mint 21.1.

`flatpak run info.portfolio_performance.PortfolioPerformance`
`Gtk-Message: 11:37:56.150: Failed to load module "xapp-gtk3-module"`
`Gtk-Message: 11:37:56.451: Failed to load module "xapp-gtk3-module"`

`(java:22): Gdk-WARNING **: 11:37:56.825: The program 'java' received an X Window System error.`
`This probably reflects a bug in the program.`
`The error was 'BadAccess (attempt to access private resource denied)'.`
`  (Details: serial 211 error_code 10 request_code 131 (MIT-SHM) minor_code 1)`

![Screenshot 2023-01-15 120043](https://user-images.githubusercontent.com/53393858/212536911-12908f3f-273d-4942-b563-db7727e63078.png)

**Comment by buchen** [comment]
Which JDK/JRE are you using?

**Comment by peastea** [comment]
I have tried with openjdk-11-jdk and 17.

java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)

java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)

**Comment by roshanshariff** [comment]
The version of openjdk in your host environment should not affect anything inside the flatpak, which uses its own self-contained java environment. I suspect that your installation might be corrupted. Can you run the following commands please, and report the output?
```sh
flatpak repair
flatpak update info.portfolio_performance.PortfolioPerformance
flatpak info info.portfolio_performance.PortfolioPerformance
flatpak run info.portfolio_performance.PortfolioPerformance
```

**Comment by peastea** [comment]
Seems to be a classical PEBCAK. Since I am running mint in a VM and somehow can't copy paste my password from my password manager in the login screen, I disabled the login password requirement. Once this is enabled everything works as intended.
