### ISSUE TITLE
after Fedora 38 upgrade flatpak only segfaults

### ISSUE THREAD

**Issue by donvipre** [flathub/info.portfolio_performance.PortfolioPerformance#60]
**Describe the bug**

After updating to Fedora 38 today from 37 the flatpak from flathub doesn't open anymore.
Immediately after executing Portfolio Performance the program crashes with:
"java quit unexpectedly" report to abrt.

**To Reproduce**
1. Update from Fedora 37 to Fedora 38
2. execute Portfolio Performance flatpak
3. Crash

**Expected behavior**
Normal execution

```bash
flatpak list | grep Portfolio
Portfolio Performance   info.portfolio_performance.PortfolioPerformance 0.62.0  stable  flathub system
cat /etc/os-release 
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by roshanshariff** [comment]
@donvipre,

I'm using the PortfolioPerformance flatpak on a system I just upgraded to Fedora 38 and it seems to be working well (using X11, not Wayland). Would you be able to run the non-Flatpak version (downloaded from its website) to see if the error is Flatpak-related or not?

Thanks!

**Comment by roshanshariff** [comment]
@donvipre it's possible that this problem is caused because we were missing a Flatpak permission. Could you try this [test build](https://github.com/flathub/info.portfolio_performance.PortfolioPerformance/pull/61#issuecomment-1518431201) to see if it resolves the issue?

**Comment by donvipre** [comment]
@roshanshariff: I executed `flatpak run --share=ipc info.portfolio_performance.PortfolioPerformance` and the program runs successfully without the error.

**Comment by roshanshariff** [comment]
Thanks @donvipre, I'll push the change making that option the default.
