### ISSUE TITLE
Consider using AppStream metadata from the project itself

### ISSUE THREAD

**Issue by buchen** [flathub/info.portfolio_performance.PortfolioPerformance#79]
As suggested in portfolio-performance/portfolio#3418, I have added the Upstream metadata XML to the project repository:

https://github.com/portfolio-performance/portfolio/blob/master/portfolio-product/appstream/info.portfolio_performance.PortfolioPerformance.metainfo.xml

I will update the file with the release notes of upcoming releases.
I also changed my release workflow to use this as the primary source for all other places where the release notes are displayed.

**Comment by roshanshariff** [comment]
Thanks @buchen! I will prepare a patch to replace our file with the upstream version. Can you also include this file in the binary releases please?

**Comment by buchen** [comment]
@roshanshariff done.

With the next release, you'll find a folder "metainfo" that contains the AppStream metainfo file.
